language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy3"
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - if ! [[ "${TRAVIS_PYTHON_VERSION}" =~ 'pypy' ]]; then
        nosetests -vv --with-coverage --cover-package=sleuth;
      else
        nosetests -vv;
      fi;
after_success:
    - if ! [[ "${TRAVIS_PYTHON_VERSION}" =~ 'pypy' ]]; then
        coveralls;
      fi;
